---
- name: Update a ServiceNow incident
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Update the ServiceNow incident
      servicenow.itsm.incident:
        number: "{{ servicenow_incident_number }}"
        state: "{{ servicenow_incident_state | default(omit, true) }}"
        other:
          work_notes: "{{ servicenow_incident_work_notes}}"
      register: servicenow_incident_result

    - name: Report the updated incident
      ansible.builtin.debug:
        msg: >-
          Incident {{ servicenow_incident_result.record.number
          | default(servicenow_incident_number) }} was updated successfully.
